// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdfkDu-LOvxuJXAheTeyLdk4MhU6l545o',
    appId: '1:827196156997:web:4772cc8e960f88aa1b872c',
    messagingSenderId: '827196156997',
    projectId: 'school-app-a22ba',
    authDomain: 'school-app-a22ba.firebaseapp.com',
    storageBucket: 'school-app-a22ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUMwKOCvxR_UkL2VzmD01U6KsBwfm8Wn4',
    appId: '1:827196156997:android:9ce26c82368c2fb81b872c',
    messagingSenderId: '827196156997',
    projectId: 'school-app-a22ba',
    storageBucket: 'school-app-a22ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCA15jNqGfGSh7FfwXcRAdJKoP0LG6CZY',
    appId: '1:827196156997:ios:30aa627af0c0d86f1b872c',
    messagingSenderId: '827196156997',
    projectId: 'school-app-a22ba',
    storageBucket: 'school-app-a22ba.appspot.com',
    iosBundleId: 'com.example.aSchoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCA15jNqGfGSh7FfwXcRAdJKoP0LG6CZY',
    appId: '1:827196156997:ios:30aa627af0c0d86f1b872c',
    messagingSenderId: '827196156997',
    projectId: 'school-app-a22ba',
    storageBucket: 'school-app-a22ba.appspot.com',
    iosBundleId: 'com.example.aSchoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdfkDu-LOvxuJXAheTeyLdk4MhU6l545o',
    appId: '1:827196156997:web:00bb1648bd742b271b872c',
    messagingSenderId: '827196156997',
    projectId: 'school-app-a22ba',
    authDomain: 'school-app-a22ba.firebaseapp.com',
    storageBucket: 'school-app-a22ba.appspot.com',
  );
}
